#!/bin/bash
#crosscontaminate in=<file,file,...> out=<file,file,...>

usage(){
	echo "Written by Brian Bushnell"
	echo "Last modified November 7, 2014"
	echo ""
	echo "Description:  Generates synthetic cross-contaminated files from clean files."
	echo "Intended for use with synthetic reads generated by RandomReads."
	echo ""
	echo "Usage:	crosscontaminate.sh in=<file,file,...> out=<file,file,...>"
	echo ""
	echo "Input and output may be a fasta or fastq files, compressed or uncompressed."
	echo ""
	echo "Parameters and their defaults:"
	echo ""
	echo "Input parameters:"
	echo "in=<file,file,...>	Clean input reads."
	echo "innamefile=<file>	A file containing the names of input files, one name per line."
	echo "interleaved=auto 	(int) t/f overrides interleaved autodetection."
	echo "qin=auto         	Input quality offset: 33 (Sanger), 64, or auto."
	echo "reads=-1         	If positive, quit after processing X reads or pairs."
	echo ""
	echo "Processing Parameters:"
	echo "minsinks=1            Min contamination destinations from one source."
	echo "maxsinks=8            Max contamination destinations from one source."
	echo "minprob=0.000005      Min allowed contamination rate (geometric distribution)."
	echo "maxprob=0.025         Max allowed contamination rate."
	echo ""
	echo "Output parameters:"
	echo "out=<file,file,...>	Contaminated output reads."
	echo "outnamefile=<file>	A file containing the names of output files, one name per line."
	echo "overwrite=t      	(ow) Grant permission to overwrite files."
#	echo "showspeed=t      	(ss) 'f' suppresses display of processing speed."
	echo "ziplevel=2       	(zl) Compression level; 1 (min) through 9 (max)."
	echo "threads=auto     	(t) Set number of threads to use; default is number of logical processors."
	echo "qout=auto        	Output quality offset: 33 (Sanger), 64, or auto."
	echo "shuffle=f        	Shuffle contents of output files."
	echo "shufflethreads=3	Use this many threads for shuffling (requires more memory)."
	echo ""
	echo "Java Parameters:"
	echo "-Xmx       		This will be passed to Java to set memory usage, overriding the program's automatic memory detection."
	echo "				-Xmx20g will specify 20 gigs of RAM, and -Xmx200m will specify 200 megs.  The max is typically 85% of physical memory."
	echo ""
	echo "There is a changelog at /global/projectb/sandbox/gaag/bbtools/docs/changelog_crosscontaminate.txt"
	echo "Please contact Brian Bushnell at bbushnell@lbl.gov if you encounter any problems."
	echo ""
}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/"
CP="$DIR""current/"

z="-Xmx4g"
z2="-Xms4g"
EA="-ea"
set=0

if [ -z "$1" ] || [[ $1 == -h ]] || [[ $1 == --help ]]; then
	usage
	exit
fi

calcXmx () {
	source "$DIR""/calcmem.sh"
	parseXmx "$@"
	if [[ $set == 1 ]]; then
		return
	fi
	freeRam 4000m 42
	z="-Xmx${RAM}m"
}
calcXmx "$@"

crosscontaminate() {
	#module unload oracle-jdk
	#module load oracle-jdk/1.7_64bit
	#module load pigz
	local CMD="java $EA $z -cp $CP jgi.CrossContaminate $@"
	echo $CMD >&2
	$CMD
}

crosscontaminate "$@"
